name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_URL: ${{ secrets.NEXUS_URL }}
          NEXUS_REPOSITORY_ID: ${{ secrets.NEXUS_REPOSITORY_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11' # Specify your desired Java version here
          distribution: 'adopt' # Use 'adopt' distribution for OpenJDK
          cache: maven

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install maven -y


      - name: Unit Testing
        run: mvn test

      - name: Integration Testing
        run: mvn verify -DskipTests

      - name: Maven Build
        run: mvn clean install 

      - name: Static Code Analysis with SonarQube
        run: mvn clean package sonar:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Quality Gate Status
        run: |
          mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar \
             -Dsonar.login=${{ secrets.SONAR_LOGIN }} \
             -Dsonar.password=${{ secrets.SONAR_PASSWORD }} \
             -Dsonar.projectKey=com.example:springboot \
             -Dsonar.sources=${{ secrets.SONAR_SOURCES }} \
             -Dsonar.tests=${{ secrets.SONAR_TESTS }} \
             
      - name: Upload WAR file to Nexus
        run: |
          mvn deploy:deploy-file \
            -Durl="${NEXUS_URL}" \
            -DrepositoryId="${NEXUS_REPOSITORY_ID}" \
            -Dfile=target/Uber.jar \
            -DgroupId=com.example \
            -DartifactId=springboot \
            -Dversion=${{ steps.read_version.outputs.version }} \
            -Dpackaging=jar \
            -Dclassifier= \
            -DgeneratePom=false

      - name: Docker Image Build
        run: |
          docker build -t ${{ github.repository }}:v1.${{ github.run_number }} .
          docker tag ${{ github.repository }}:v1.${{ github.run_number }} vishalkalchuri/${{ github.repository }}:v1.${{ github.run_number }}
          docker tag ${{ github.repository }}:v1.${{ github.run_number }} vishalkalchuri/${{ github.repository }}:latest
          docker push vishalkalchuri/${{ github.repository }}:v1.${{ github.run_number }}
          docker push vishalkalchuri/${{ github.repository }}:latest
